#coding:utf-8
##################################################
# file: SchoolInfoService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /home/farhad/job/eduschl/src/web_edu/wsdl2py.py -b ./info.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from SchoolInfoService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
listUnitKindsRequest = GED("urn:bars-web-school-info", "listUnitKindsRequest").pyclass

listUnitKindsResponse = GED("urn:bars-web-school-info", "listUnitKindsResponse").pyclass

listUnitsRequest = GED("urn:bars-web-school-info", "listUnitsRequest").pyclass

listUnitsResponse = GED("urn:bars-web-school-info", "listUnitsResponse").pyclass

unitsInfoRequest = GED("urn:bars-web-school-info", "unitsInfoRequest").pyclass

unitsInfoResponse = GED("urn:bars-web-school-info", "unitsInfoResponse").pyclass

unitDetailsRequest = GED("urn:bars-web-school-info", "unitDetailsRequest").pyclass

unitDetailsResponse = GED("urn:bars-web-school-info", "unitDetailsResponse").pyclass

listUnitTypesRequest = GED("urn:bars-web-school-info", "listUnitTypesRequest").pyclass

listUnitTypesResponse = GED("urn:bars-web-school-info", "listUnitTypesResponse").pyclass

listTerritoriesRequest = GED("urn:bars-web-school-info", "listTerritoriesRequest").pyclass

listTerritoriesResponse = GED("urn:bars-web-school-info", "listTerritoriesResponse").pyclass


# Service Skeletons
class SchoolInfoService(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = u"""<?xml version=\"1.0\" ?>
<definitions name=\"SchoolInfoService\" targetNamespace=\"urn:bars-web-school-info\" xmlns=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:tns=\"urn:bars-web-school-info\" xmlns:wsam=\"http://www.w3.org/2007/05/addressing/metadata\" xmlns:wsp=\"http://www.w3.org/ns/ws-policy\" xmlns:wsp1_2=\"http://schemas.xmlsoap.org/ws/2004/09/policy\" xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">
    <types>
<xsd:schema elementFormDefault=\"qualified\" targetNamespace=\"urn:bars-web-school-info\" xmlns:tns=\"urn:bars-web-school-info\" xmlns:xmime=\"http://www.w3.org/2005/05/xmlmime\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">
  <xsd:complexType name=\"Any\">
    <xsd:sequence>
      <xsd:any maxOccurs=\"unbounded\" minOccurs=\"0\" namespace=\"##any\" processContents=\"lax\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:simpleType name=\"Inn\">
    <xsd:restriction base=\"xsd:normalizedString\">
      <xsd:length value=\"10\"/>
      <xsd:pattern value=\"[0-9]\"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name=\"AuthToken\">
    <xsd:restriction base=\"xsd:token\">
      <xsd:minLength value=\"1\"/>
      <xsd:maxLength value=\"255\"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name=\"String\">
    <xsd:restriction base=\"xsd:normalizedString\">
      <xsd:minLength value=\"1\"/>
      <xsd:maxLength value=\"255\"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name=\"Error\">
    <xsd:sequence>
      <xsd:element name=\"errorCode\" type=\"xsd:long\"/>
      <xsd:element name=\"errorMessage\" type=\"tns:String\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=\"Employee\">
    <xsd:sequence>
      <xsd:element name=\"sname\" type=\"xsd:string\"/>
      <xsd:element name=\"fname\" type=\"xsd:string\"/>
      <xsd:element name=\"mname\" type=\"xsd:string\"/>
      <xsd:element name=\"position\" type=\"xsd:string\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=\"ResultArtefact\">
    <xsd:sequence>
      <xsd:element name=\"documentId\" type=\"xsd:string\"/>
      <xsd:element name=\"mimeType\" type=\"xsd:string\"/>
      <xsd:element name=\"documentTypeCode\" type=\"xsd:string\"/>
      <xsd:element minOccurs=\"0\" name=\"documentName\" type=\"xsd:string\"/>
      <xsd:element minOccurs=\"0\" name=\"text\" type=\"xsd:string\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=\"Document\">
    <xsd:complexContent>
      <xsd:extension base=\"tns:ResultArtefact\">
        <xsd:sequence>
          <xsd:element minOccurs=\"0\" name=\"content\" type=\"xsd:base64Binary\" xmime:expectedContentTypes=\"application/octet-stream\"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name=\"Url\">
    <xsd:complexContent>
      <xsd:extension base=\"tns:ResultArtefact\">
        <xsd:sequence>
          <xsd:element minOccurs=\"0\" name=\"url\" type=\"xsd:normalizedString\"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name=\"Documents\">
    <xsd:sequence>
      <xsd:element maxOccurs=\"unbounded\" name=\"document\" type=\"tns:Document\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=\"Urls\">
    <xsd:sequence>
      <xsd:element maxOccurs=\"unbounded\" name=\"url\" type=\"tns:Url\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=\"OrgExternal\">
    <xsd:sequence>
      <xsd:element name=\"regionCode\" type=\"xsd:string\"/>
      <xsd:element name=\"serviceOrgCode\" type=\"xsd:string\"/>
      <xsd:element minOccurs=\"0\" name=\"employee\" type=\"tns:Employee\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=\"RequestHeader\">
    <xsd:sequence>
      <xsd:element name=\"authToken\" type=\"tns:AuthToken\"/>
      <xsd:element name=\"requestId\" type=\"tns:String\"/>
      <xsd:element name=\"requestInitiatorCode\" type=\"tns:OrgExternal\"/>
      <xsd:element name=\"orgRegistrator\" type=\"tns:OrgExternal\"/>
      <xsd:element name=\"requestTypeCode\" type=\"tns:String\"/>
      <xsd:element name=\"requestDate\" type=\"xsd:dateTime\"/>
      <xsd:element name=\"documents\" type=\"tns:Documents\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=\"EServiceHeader\">
    <xsd:sequence>
      <xsd:element name=\"userId\" type=\"xsd:long\"/>
      <xsd:element name=\"eserviceId\" type=\"xsd:long\"/>
      <xsd:element name=\"reestrId\" type=\"tns:String\"/>
      <xsd:element name=\"stateOrgId\" type=\"xsd:long\"/>
      <xsd:element name=\"orderDate\" type=\"xsd:date\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=\"ResponseHeader\">
    <xsd:sequence>
      <xsd:element name=\"authToken\" type=\"tns:AuthToken\"/>
      <xsd:element name=\"responseDate\" type=\"xsd:dateTime\"/>
      <xsd:element name=\"requestInitiatorCode\" type=\"tns:OrgExternal\"/>
      <xsd:element name=\"requestIDRef\" type=\"tns:String\"/>
      <xsd:element name=\"error\" type=\"tns:Error\"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=\"EServiceResult\">
    <xsd:sequence>
      <xsd:element name=\"orderStatusId\" type=\"tns:String\"/>
<xsd:element name=\"comment\" type=\"tns:String\"/>
      <xsd:element minOccurs=\"0\" name=\"extOrderNumber\" type=\"tns:String\"/>
      <xsd:element minOccurs=\"0\" name=\"urls\" type=\"tns:Urls\"/>
      <xsd:element minOccurs=\"0\" name=\"documents\" type=\"tns:Documents\"/>
      <xsd:element minOccurs=\"0\" name=\"XML\" type=\"tns:Any\"/>
    </xsd:sequence>
  </xsd:complexType>

<!-- begin  kinds-->
            <xsd:element name=\"listUnitKindsRequest\" type=\"tns:listUnitKindsRequest\">
                <xsd:annotation><xsd:documentation>Запрос списка видов учреждений</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:element name=\"listUnitKindsResponse\" type=\"tns:listUnitKindsResponse\">
                <xsd:annotation><xsd:documentation>Ответ на запрос списка видов учреждений</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:complexType name=\"listUnitKindsRequest\">
                <xsd:annotation><xsd:documentation>Параметры запроса списка видов учреждений</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"requestHeader\" type=\"tns:RequestHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceHeader\" type=\"tns:EServiceHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"unitType\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Список идентификаторов объектов &quot;Тип учреждения&quot;</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"listUnitKindsResponse\">
                <xsd:annotation><xsd:documentation>Параметры ответа на запрос списка видов учреждений</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"responseHeader\" type=\"tns:ResponseHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceResult\" type=\"tns:EServiceResult\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"returns\" type=\"tns:unitKind\">
                        <xsd:annotation><xsd:documentation>Список объектов &quot;Вид учреждения&quot;</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"unitKind\">
                <xsd:annotation><xsd:documentation>Описание объекта &quot;Вид учреждения&quot;</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element name=\"name\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Наименование вида</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"id\" type=\"xsd:integer\">
                        <xsd:annotation><xsd:documentation>Идентификатор вида</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
<!-- end  kinds-->

<!-- begin units-->
            <xsd:element name=\"listUnitsRequest\" type=\"tns:listUnitsRequest\">
                <xsd:annotation><xsd:documentation>Запрос списка учреждений</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:element name=\"listUnitsResponse\" type=\"tns:listUnitsResponse\">
                <xsd:annotation><xsd:documentation>Ответ на запрос списка учреждений</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:complexType name=\"listUnitsRequest\">
                <xsd:annotation><xsd:documentation>Параметры запроса списка учреждений</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"requestHeader\" type=\"tns:RequestHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceHeader\" type=\"tns:EServiceHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"types\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Список идентификаторов типов учреждений</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"kinds\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Список идентификаторов видов учреждений</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"areas\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Список идентификаторов территорий учреждений</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"listUnitsResponse\">
                <xsd:annotation><xsd:documentation>Параметры ответа на запрос списка учреждений</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"responseHeader\" type=\"tns:ResponseHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceResult\" type=\"tns:EServiceResult\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"returns\" type=\"tns:unit\">
                        <xsd:annotation><xsd:documentation>Список объектов &quot;Учреждение&quot;</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"unit\">
                <xsd:annotation><xsd:documentation>Описание объекта &quot;Учреждение&quot;</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element name=\"name\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Наименование</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"id\" type=\"xsd:integer\">
                        <xsd:annotation><xsd:documentation>Идентификатор</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>



            <xsd:element name=\"unitsInfoRequest\" type=\"tns:unitsInfoRequest\">
                <xsd:annotation><xsd:documentation>Запрос информации об учреждениях</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:element name=\"unitsInfoResponse\" type=\"tns:unitsInfoResponse\">
                <xsd:annotation><xsd:documentation>Ответ на запрос информации об учреждениях</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:complexType name=\"unitsInfoRequest\">
                <xsd:annotation><xsd:documentation>Параметры запроса информации об учреждениях</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"requestHeader\" type=\"tns:RequestHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceHeader\" type=\"tns:EServiceHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"units\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Список идентификаторов учреждений по которым необходима информация</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"unitsInfoResponse\">
                <xsd:annotation><xsd:documentation>Параметры ответа на запрос информации об учреждениях</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"responseHeader\" type=\"tns:ResponseHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceResult\" type=\"tns:EServiceResult\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"returns\" type=\"tns:unitInfo\">
                        <xsd:annotation><xsd:documentation>Список объектов &quot;Информация об учреждении&quot;</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"unitInfo\">
                <xsd:annotation><xsd:documentation>Описание объекта &quot;Информация об учреждении&quot;</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element name=\"id\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Идентификатор</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"name\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Наименование</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"address\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Адрес</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"telephone\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Телефон</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"email\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Email</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"web_page\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Адрес сайта в интернете</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"director\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Директор</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>



            <xsd:element name=\"unitDetailsRequest\" type=\"tns:unitDetailsRequest\">
                <xsd:annotation><xsd:documentation>Запрос расширенной информации об учреждении</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:element name=\"unitDetailsResponse\" type=\"tns:unitDetailsResponse\">
                <xsd:annotation><xsd:documentation>Ответ на запрос расширенной информации об учреждении</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:complexType name=\"unitDetailsRequest\">
                <xsd:annotation><xsd:documentation>Параметры запроса расширенной информации об учреждении</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"requestHeader\" type=\"tns:RequestHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceHeader\" type=\"tns:EServiceHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"unit\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Идентификатор учреждения по которым необходима расширенная информация</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"format\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Формат возвращаемой информации (html, json, по умолчанию html)</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"unitDetailsResponse\">
                <xsd:annotation><xsd:documentation>Параметры ответа на запрос расширенной информации об учреждении</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"responseHeader\" type=\"tns:ResponseHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceResult\" type=\"tns:EServiceResult\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"returns\" nillable=\"true\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Страница расширенной информации об учреждении</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
<!-- end  units-->
<!-- begin types-->
            <xsd:element name=\"listUnitTypesRequest\" type=\"tns:listUnitTypesRequest\">
                <xsd:annotation><xsd:documentation>Запрос списка типов учреждений</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:element name=\"listUnitTypesResponse\" type=\"tns:listUnitTypesResponse\">
                <xsd:annotation><xsd:documentation>Ответ на запрос списка типов учреждений</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:complexType name=\"listUnitTypesRequest\">
                <xsd:annotation><xsd:documentation>Параметры запроса списка типов учреждений</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"requestHeader\" type=\"tns:RequestHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceHeader\" type=\"tns:EServiceHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"AreaId\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>ОКАТО Района</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"listUnitTypesResponse\">
                <xsd:annotation><xsd:documentation>Параметры ответа на запрос списка типов учреждений</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"responseHeader\" type=\"tns:ResponseHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceResult\" type=\"tns:EServiceResult\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"returns\" type=\"tns:unitType\">
                        <xsd:annotation><xsd:documentation>Список объектов &quot;Тип учреждения&quot;</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"unitType\">
                <xsd:annotation><xsd:documentation>Описание объекта &quot;Тип учреждения&quot;</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element name=\"name\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Наименование типа</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"id\" type=\"xsd:integer\">
                        <xsd:annotation><xsd:documentation>Идентификатор типа</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
<!-- end  types-->
<!-- begin territories-->
            <xsd:element name=\"listTerritoriesRequest\" type=\"tns:listTerritoriesRequest\">
                <xsd:annotation><xsd:documentation>Запрос списка территорий</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:element name=\"listTerritoriesResponse\" type=\"tns:listTerritoriesResponse\">
                <xsd:annotation><xsd:documentation>Ответ на запрос списка территорий</xsd:documentation></xsd:annotation>
            </xsd:element>

            <xsd:complexType name=\"listTerritoriesRequest\">
                <xsd:annotation><xsd:documentation>Параметры запроса списка территорий</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"requestHeader\" type=\"tns:RequestHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceHeader\" type=\"tns:EServiceHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок запроса eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"listTerritoriesResponse\">
                <xsd:annotation><xsd:documentation>Параметры ответа на запрос списка территорий</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs=\"0\" name=\"responseHeader\" type=\"tns:ResponseHeader\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs=\"0\" name=\"eServiceResult\" type=\"tns:EServiceResult\">
                        <xsd:annotation><xsd:documentation>Заголовок ответа eServiceHeader</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"returns\" type=\"tns:Territory\">
                        <xsd:annotation><xsd:documentation>Список объектов &quot;Территория&quot;</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name=\"Territory\">
                <xsd:annotation><xsd:documentation>Описание объекта &quot;Территория&quot;</xsd:documentation></xsd:annotation>
                <xsd:sequence>
                    <xsd:element name=\"name\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>Наименование территории</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"id\" type=\"xsd:integer\">
                        <xsd:annotation><xsd:documentation>Идентификатор территории</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element name=\"okato\" type=\"xsd:string\">
                        <xsd:annotation><xsd:documentation>ОКАТО территории</xsd:documentation></xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

<!-- end territories-->
        </xsd:schema>
    </types>
<!-- begin  kinds-->
    <message name=\"listUnitKindsRequest\">
        <part element=\"tns:listUnitKindsRequest\" name=\"parameters\"/>
    </message>
    <message name=\"listUnitKindsResponse\">
        <part element=\"tns:listUnitKindsResponse\" name=\"parameters\"/>
    </message>
    <portType name=\"listUnitKindsPortType\">
        <operation name=\"listUnitKindsOper\">
            <documentation>Операция получения списка видов учреждений</documentation>
            <input message=\"tns:listUnitKindsRequest\" wsam:Action=\"urn:listUnitKindsRequest\"/>
            <output message=\"tns:listUnitKindsResponse\" wsam:Action=\"urn:listUnitKindsResponse\"/>
        </operation>
    </portType>
    <binding name=\"listUnitKindsPortBinding\" type=\"tns:listUnitKindsPortType\">
        <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
        <operation name=\"listUnitKindsOper\">
            <soap:operation soapAction=\"urn:listUnitKindsOper\"/>
            <input>
                <soap:body use=\"literal\"/>
            </input>
            <output>
                <soap:body use=\"literal\"/>
            </output>
        </operation>
    </binding>
<!-- end  kinds-->
<!-- begin units-->
    <message name=\"listUnitsRequest\">
        <part element=\"tns:listUnitsRequest\" name=\"parameters\"/>
    </message>
    <message name=\"listUnitsResponse\">
        <part element=\"tns:listUnitsResponse\" name=\"parameters\"/>
    </message>
    <message name=\"unitsInfoRequest\">
        <part element=\"tns:unitsInfoRequest\" name=\"parameters\"/>
    </message>
    <message name=\"unitsInfoResponse\">
        <part element=\"tns:unitsInfoResponse\" name=\"parameters\"/>
    </message>
    <message name=\"unitDetailsRequest\">
        <part element=\"tns:unitDetailsRequest\" name=\"parameters\"/>
    </message>
    <message name=\"unitDetailsResponse\">
        <part element=\"tns:unitDetailsResponse\" name=\"parameters\"/>
    </message>
    <portType name=\"listUnitsPortType\">
        <operation name=\"listUnitsOper\">
            <documentation>Операция получения списка учреждений</documentation>
            <input message=\"tns:listUnitsRequest\" wsam:Action=\"urn:listUnitsRequest\"/>
            <output message=\"tns:listUnitsResponse\" wsam:Action=\"urn:listUnitsResponse\"/>
        </operation>
        <operation name=\"unitsInfoOper\">
            <documentation>Операция получения информации об учреждениях</documentation>
            <input message=\"tns:unitsInfoRequest\" wsam:Action=\"urn:unitsInfoRequest\"/>
            <output message=\"tns:unitsInfoResponse\" wsam:Action=\"urn:unitsInfoResponse\"/>
        </operation>
        <operation name=\"unitDetailsOper\">
            <documentation>Операция получения информации об учреждениях</documentation>
            <input message=\"tns:unitDetailsRequest\" wsam:Action=\"urn:unitDetailsRequest\"/>
            <output message=\"tns:unitDetailsResponse\" wsam:Action=\"urn:unitDetailsResponse\"/>
        </operation>
    </portType>
    <binding name=\"listUnitsPortBinding\" type=\"tns:listUnitsPortType\">
        <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
        <operation name=\"listUnitsOper\">
            <soap:operation soapAction=\"urn:listUnitsOper\"/>
            <input>
                <soap:body use=\"literal\"/>
            </input>
            <output>
                <soap:body use=\"literal\"/>
            </output>
        </operation>
        <operation name=\"unitsInfoOper\">
            <soap:operation soapAction=\"urn:unitsInfoOper\"/>
            <input>
                <soap:body use=\"literal\"/>
            </input>
            <output>
                <soap:body use=\"literal\"/>
            </output>
        </operation>
        <operation name=\"unitDetailsOper\">
            <soap:operation soapAction=\"urn:unitDetailsOper\"/>
            <input>
                <soap:body use=\"literal\"/>
            </input>
            <output>
                <soap:body use=\"literal\"/>
            </output>
        </operation>
    </binding>
<!-- end units-->
<!-- begin types-->
    <message name=\"listUnitTypesRequest\">
        <part element=\"tns:listUnitTypesRequest\" name=\"parameters\"/>
    </message>
    <message name=\"listUnitTypesResponse\">
        <part element=\"tns:listUnitTypesResponse\" name=\"parameters\"/>
    </message>
    <portType name=\"listUnitTypesPortType\">
        <operation name=\"listUnitTypesOper\">
            <documentation>Операция получения списка типов учреждений</documentation>
            <input message=\"tns:listUnitTypesRequest\" wsam:Action=\"urn:listUnitTypesRequest\"/>
            <output message=\"tns:listUnitTypesResponse\" wsam:Action=\"urn:listUnitTypesResponse\"/>
        </operation>
    </portType>
    <binding name=\"listUnitTypesPortBinding\" type=\"tns:listUnitTypesPortType\">
        <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
        <operation name=\"listUnitTypesOper\">
            <soap:operation soapAction=\"urn:listUnitTypesOper\"/>
            <input>
                <soap:body use=\"literal\"/>
            </input>
            <output>
                <soap:body use=\"literal\"/>
            </output>
        </operation>
    </binding>
<!-- end types-->
<!-- begin territories-->
    <message name=\"listTerritoriesRequest\">
        <part element=\"tns:listTerritoriesRequest\" name=\"parameters\"/>
    </message>
    <message name=\"listTerritoriesResponse\">
        <part element=\"tns:listTerritoriesResponse\" name=\"parameters\"/>
    </message>
    <portType name=\"listTerritoriesPortType\">
        <operation name=\"listTerritoriesOper\">
            <documentation>Операция получения списка территорий</documentation>
            <input message=\"tns:listTerritoriesRequest\" wsam:Action=\"urn:listTerritoriesRequest\"/>
            <output message=\"tns:listTerritoriesResponse\" wsam:Action=\"urn:listTerritoriesResponse\"/>
        </operation>
    </portType>
    <binding name=\"listTerritoriesPortBinding\" type=\"tns:listTerritoriesPortType\">
        <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
        <operation name=\"listTerritoriesOper\">
            <soap:operation soapAction=\"urn:listTerritoriesOper\"/>
            <input>
                <soap:body use=\"literal\"/>
            </input>
            <output>
                <soap:body use=\"literal\"/>
            </output>
        </operation>
    </binding>
<!-- end territories-->

    <service name=\"SchoolInfoService\">
        <port binding=\"tns:listUnitKindsPortBinding\" name=\"listUnitKindsPort\">
            <soap:address location=\"http://localhost:9080/stdws/unitkinds\"/>
        </port>
        <port binding=\"tns:listUnitsPortBinding\" name=\"listUnitsPort\">
            <soap:address location=\"http://localhost:9080/stdws/units\"/>
        </port>
        <port binding=\"tns:listUnitTypesPortBinding\" name=\"listUnitTypesPort\">
            <soap:address location=\"http://localhost:9080/stdws/unittypes\"/>
        </port>
        <port binding=\"tns:listTerritoriesPortBinding\" name=\"listTerritoriesPort\">
            <soap:address location=\"http://localhost:9080/stdws/unittypes\"/>
        </port>

    </service>
</definitions>"""

    def __init__(self, post='/stdws/unittypes', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_listUnitKindsOper(self, ps, **kw):
        request = ps.Parse(listUnitKindsRequest.typecode)
        return request,listUnitKindsResponse()

    soapAction['urn:listUnitKindsOper'] = 'soap_listUnitKindsOper'
    root[(listUnitKindsRequest.typecode.nspname,listUnitKindsRequest.typecode.pname)] = 'soap_listUnitKindsOper'

    def soap_listUnitsOper(self, ps, **kw):
        request = ps.Parse(listUnitsRequest.typecode)
        return request,listUnitsResponse()

    soapAction['urn:listUnitsOper'] = 'soap_listUnitsOper'
    root[(listUnitsRequest.typecode.nspname,listUnitsRequest.typecode.pname)] = 'soap_listUnitsOper'

    def soap_unitsInfoOper(self, ps, **kw):
        request = ps.Parse(unitsInfoRequest.typecode)
        return request,unitsInfoResponse()

    soapAction['urn:unitsInfoOper'] = 'soap_unitsInfoOper'
    root[(unitsInfoRequest.typecode.nspname,unitsInfoRequest.typecode.pname)] = 'soap_unitsInfoOper'

    def soap_unitDetailsOper(self, ps, **kw):
        request = ps.Parse(unitDetailsRequest.typecode)
        return request,unitDetailsResponse()

    soapAction['urn:unitDetailsOper'] = 'soap_unitDetailsOper'
    root[(unitDetailsRequest.typecode.nspname,unitDetailsRequest.typecode.pname)] = 'soap_unitDetailsOper'

    def soap_listUnitTypesOper(self, ps, **kw):
        request = ps.Parse(listUnitTypesRequest.typecode)
        return request,listUnitTypesResponse()

    soapAction['urn:listUnitTypesOper'] = 'soap_listUnitTypesOper'
    root[(listUnitTypesRequest.typecode.nspname,listUnitTypesRequest.typecode.pname)] = 'soap_listUnitTypesOper'

    def soap_listTerritoriesOper(self, ps, **kw):
        request = ps.Parse(listTerritoriesRequest.typecode)
        return request,listTerritoriesResponse()

    soapAction['urn:listTerritoriesOper'] = 'soap_listTerritoriesOper'
    root[(listTerritoriesRequest.typecode.nspname,listTerritoriesRequest.typecode.pname)] = 'soap_listTerritoriesOper'

